apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-statefulset
  labels:
    app: nginx
    controller.limits.thanos.io: "true"
spec:
  serviceName: "nginx"
  replicas: 5
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
          name: web
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 60  # Wait 3 minutes before probing
          periodSeconds: 10         # Retry every 10 seconds
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
