apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-statefulset
  labels:
    app: nginx
    controller.limits.thanos.io: "thanos-limits-controller"
spec:
  serviceName: "nginx"
  replicas: 3
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
          name: web
